version: '3.5'

services:
  traefik:
    image: traefik:2.0 # The official Traefik docker image
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./config/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - gateway

networks:
    gateway:
        name: traefik_gateway
